name: Continuous Integration

on:
  push:
    branches:
      - main

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
      - name: Build project
        run: |
      - name: Run unit tests
        run: |
         
